# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 06:23
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('brand_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('brand_name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 6, 23, 6, 379745), null=True)),
                ('brand_status', models.CharField(choices=[(b'1', b'1'), (b'0', b'0')], default=b'1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 6, 23, 6, 379238), null=True)),
                ('category_status', models.CharField(choices=[(b'1', b'1'), (b'0', b'0')], default=b'1', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('customer_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('customer_first_name', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_email', models.CharField(blank=True, max_length=45, null=True)),
                ('customer_status', models.CharField(choices=[(b'1', b'1'), (b'0', b'0')], default=b'1', max_length=1)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 6, 23, 6, 378239), null=True)),
                ('fb_token', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter_token', models.CharField(blank=True, max_length=100, null=True)),
                ('google_token', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
