# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 11:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingapp', '0002_auto_20160830_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 11, 53, 36, 771286), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 11, 53, 36, 770787), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 11, 53, 36, 769870), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 11, 53, 36, 771736), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 11, 53, 36, 772537), null=True),
        ),
    ]
