# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 14:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingapp', '0004_auto_20160830_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 14, 55, 428756), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 14, 55, 428244), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 14, 55, 427340), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 14, 55, 429203), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 14, 55, 429755), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_availability',
            field=models.CharField(choices=[(b'In Stock', b'1'), (b'Out Of Stock', b'0')], default=b'1', max_length=1),
        ),
    ]
