# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingapp', '0005_auto_20160830_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_id',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='Shoppingapp.Brand'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 35, 19, 670026), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 35, 19, 669526), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 35, 19, 668611), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 35, 19, 670551), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 35, 19, 671184), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='product_availability',
            field=models.CharField(choices=[(b'1', b'In Stock'), (b'0', b'Out Of Stock')], default=b'1', max_length=1),
        ),
    ]
