# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-30 14:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingapp', '0006_auto_20160830_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdetail',
            name='product_quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 44, 24, 762356), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 44, 24, 761860), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 44, 24, 760953), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 44, 24, 762883), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 8, 30, 14, 44, 24, 763515), null=True),
        ),
    ]
