# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-09-01 10:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Shoppingapp', '0007_auto_20160830_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReviews',
            fields=[
                ('product_review_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=45, null=True)),
                ('user_email', models.CharField(blank=True, max_length=45, null=True)),
                ('user_review', models.CharField(blank=True, max_length=45, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 763053), null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 760843), null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 760341), null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 759395), null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 761408), null=True),
        ),
        migrations.AlterField(
            model_name='productdetail',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 9, 1, 10, 8, 17, 762041), null=True),
        ),
        migrations.AddField(
            model_name='productreviews',
            name='product_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='Shoppingapp.Product'),
        ),
    ]
